
import Head from "next/head"
import Dashboard from "./dashboard";

export default function Home() {

  return (
    <>
      <Head>
        <title>TMR BEAR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="Content-Security-Policy" />
        <link rel="icon" href="/favicon.ico" />
      
        {/* <link rel="icon" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" sizes="192x192" href="/android-chrome-192x192.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png" />
        <link rel="manifest" href="/site.webmanifest" /> */}
      </Head>
      <main> <Dashboard /> </main>
    </>
  )
}